# Generated by Django 5.1.3 on 2024-12-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recommendedtest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remark',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=4),
        ),
    ]
